export enum InvoiceType {
    ABONNEMENT = "ABONNEMENT",
    FACTURE_ELEC = "FACTURE_ELEC",
    FACTURE_EAU = "FACTURE_EAU",
    FACTURE_MAINTENANCE = "FACTURE_MAINTENANCE",
    FACTURE_LOYER = "FACTURE_LOYER"
}